### PR TITLE
Added GetMock method and dictionary.

### PR DESCRIPTION
**Pull request by luetm**
I use it like this:
// * Arrange
var fixture = new Fixture();
var appointment = fixture.GetNoPatientInfo(MedikalAction.Creation);
var sut = fixture
	.FakeAppointments()
	.Build();

// * Act
sut.Add(staffId, appointment);

// * Assert
var mock = MockExtensions.GetMockDbSet< Appointment >();
mock.Verify(x => x.Add(It.Is<PatientAppointment>(a => a.StaffId == staffId)));

### CODE REVIEW

**Comment by fredrikholm** [comment]
Good job! Thanks for contributing. :-)

**Comment by luetm** [comment]
Thanks for the quick reply! I know it's not perfect where it is but I guess it's simplest that way.

**Comment by luetm** [comment]
By the way, can you let me know, when you update the nuget package, please?

**Comment by fredrikholm** [comment]
Sure, just uploaded it and bumped the version to 1.1.0. Not sure how long it takes until it’s published though…

Cheers /Fredrik

**Comment by luetm** [comment]
Thanks! :)

**Pull request merged**
